Update to urllib3 1.26.13
Module version is required urllib3 1.26.13 but it is installing non-dependent module version urllib3 2.0.0a2
```
error: urllib3 2.0.0a2 is installed but urllib3<1.27,>=1.21.1 is required by {'requests'}
```